"""Initial migration

Revision ID: 536598dab20b
Revises: 
Create Date: 2025-10-02 11:55:38.073977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '536598dab20b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saga_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('yaml_content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='sagaconfigurationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saga_configurations_id'), 'saga_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_saga_configurations_name'), 'saga_configurations', ['name'], unique=True)
    op.create_table('saga_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saga_configuration_id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'ROLLED_BACK', name='sagaexecutionstatus'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['saga_configuration_id'], ['saga_configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saga_executions_correlation_id'), 'saga_executions', ['correlation_id'], unique=True)
    op.create_index(op.f('ix_saga_executions_id'), 'saga_executions', ['id'], unique=False)
    op.create_table('saga_execution_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saga_execution_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'ROLLED_BACK', 'SKIPPED', name='sagaexecutionstepstatus'), nullable=False),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['saga_execution_id'], ['saga_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saga_execution_steps_id'), 'saga_execution_steps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saga_execution_steps_id'), table_name='saga_execution_steps')
    op.drop_table('saga_execution_steps')
    op.drop_index(op.f('ix_saga_executions_id'), table_name='saga_executions')
    op.drop_index(op.f('ix_saga_executions_correlation_id'), table_name='saga_executions')
    op.drop_table('saga_executions')
    op.drop_index(op.f('ix_saga_configurations_name'), table_name='saga_configurations')
    op.drop_index(op.f('ix_saga_configurations_id'), table_name='saga_configurations')
    op.drop_table('saga_configurations')
    # ### end Alembic commands ###
